import { ExchangeMetadata, Network, Order, UnhashedOrder } from '../types';
export declare function checkSenderOfAuthenticatedProxy(exchangeContract: any, authenticatedProxyContract: any, proxyRegistryContract: any, account: string): Promise<boolean>;
export declare function checkRegisterProxy(proxyRegistryContract: any, account: string): Promise<boolean>;
export declare function checkApproveTokenTransferProxy(exchangeContract: any, erc20Contract: any, account: string): Promise<boolean>;
export declare function checkApproveERC1155TransferProxy(proxyRegistryContract: any, nftsContract: any, account: string): Promise<boolean>;
export declare function checkApproveERC721TransferProxy(proxyRegistryContract: any, nftsContract: any, account: string, tokenID: string): Promise<boolean>;
export declare function checkUnhashedOrder(contract: any, order: UnhashedOrder): Promise<boolean>;
export declare function checkOrder(contract: any, order: Order): Promise<boolean>;
export declare function checkMatchOrder(contract: any, buy: Order, sell: Order): Promise<boolean>;
export declare function checkDataToCall(netWorkName: Network, order: UnhashedOrder): void;
export declare function validateOrder(exchangeHelper: any, order: Order): Promise<any>;
export declare function validateAndFormatWalletAddress(web3: any, address: string): string;
export declare function _ordersCanMatch(buy: Order, sell: Order): boolean;
export declare function ordersCanMatch(exchangeHelper: any, buy: Order, sell: Order): Promise<any>;
export declare function checkOrderCancelledOrFinalized(contract: any, order: Order): Promise<void>;
export declare function checkAssetMint(contract: any, metadata: ExchangeMetadata): Promise<boolean>;
export declare function checkAssetApprove(contract: any, order: UnhashedOrder): Promise<any>;
export declare function checkAssetBalance(contract: any, order: UnhashedOrder): Promise<number>;
